### ISSUE TITLE
Problem with 1.1.7/1.1.8 GroovyBackend?

### ISSUE THREAD

**Issue by pblack** [cucumber/cucumber-jvm#759]
I was trying to get this gradle-cucumber-plugin working, and came a across a bug (it seems ) in the 1.1.8 release of cucumber (seems to work correctly in 1.1.6, but fails in 1.1.7 & 1.1.8).
Basically, trying to execute the gradle task, I get:

```
Caused by: java.lang.NoSuchMethodError: cucumber.runtime.io.Resource.getAbsolutePath()Ljava/lang/String;
    at cucumber.runtime.groovy.GroovyBackend.parse(GroovyBackend.java:110)
    at cucumber.runtime.groovy.GroovyBackend.loadGlue(GroovyBackend.java:74)
    at cucumber.runtime.Runtime.<init>(Runtime.java:89)
    at cucumber.runtime.Runtime.<init>(Runtime.java:67)
    at cucumber.runtime.Runtime.<init>(Runtime.java:63)
    at cucumber.api.cli.Main.run(Main.java:24)
    at cucumber.api.cli.Main.main(Main.java:16)
    at com.excella.gradle.cucumber.CucumberRunner.runCucumberTests(CucumberRunner.java:74)
    at com.excella.gradle.cucumber.CucumberRunner$runCucumberTests.call(Unknown Source)
    at com.excella.gradle.cucumber.tasks.CucumberTask.executeCucumberRunner(CucumberTask.groovy:122)
    at com.excella.gradle.cucumber.tasks.CucumberTask.cucumber(CucumberTask.groovy:50)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:570)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:553)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 44 more
```

If I revert back to 1.1.6 works, but gives an error.

Looks like it was something introduced between 1.1.6 and 1.1.7
