### ISSUE TITLE
Cucumber Data Table not able to access asMaps method. Exception:java.lang.NoSuchMethodError: cucumber.api.DataTable.asMaps()Ljava/util/List;

### ISSUE THREAD

**Issue by vinaykonke** [cucumber/cucumber-jvm#720]
I have a asMaps method which accepts cuke DataTable and converts to List of Maps. When Cucumber DataTable tries to access cuke.asMaps (where cuke is of DataTable type),then I get an exception which says,

java.lang.NoSuchMethodError: cucumber.api.DataTable.asMaps()Ljava/util/List;

This was working properly in 1.1.5 but when I upgraded my cucumber to 1.1.7 this error started showing up.

Please find an example of the code which can help you guys to reproduce the issue.

Gherkin file
Scenario: Reproducing the bug
   Given I try to convert the dataTable to map
    |name  |  sex |
    |Warner|  male|
    |emily |female| 

StepDef
 @Given("^I try to convert the dataTable to map$")
    public void I_try_to_convert_the_dataTable_to_map(DataTable cukeTable) throws Throwable {
    	 for( Map<String, String> row : cukeTable.asMaps()) {
    	    //do something
    	 }
      }

asMaps Method
  public List<Map<String, String>> asMaps() {
        return asList(new TypeReference<Map<String, String>>() {
        }.getType());
    }

**Comment by SierraGolf** [comment]
this obviously seems to be a compatibility issue when migrating form 1.1.5 to 1.1.7. since there is no answer for more then half a year, I am closing this issue as invalid.

**Comment by otaviolandim** [comment]
@aslakhellesoy 

This works in version 1.2.2?
