### ISSUE TITLE
NoSuchMethodError thrown with Scala 2.12

### ISSUE THREAD

**Issue by randomcoder** [cucumber/cucumber-jvm#1087]
## Summary
When running cucumber tests with `cucumber-scala` (1.2.5) using Scala 2.12.1 or 2.12.0 a `noSuchMethodError` is raised on startup

Here is a minimal project that reproduces the behaviour: https://github.com/randomcoder/cucumber-scala-2-12

## Expected Behavior
The test cases should run

## Current Behavior
The error below is thrown before any tests are executed

~~~
Exception in thread "main" java.lang.NoSuchMethodError: cucumber.api.scala.ScalaDsl.$init$(Lcucumber/api/scala/ScalaDsl;)V
	at steps.SimpleScenarioSteps.<init>(SimpleScenarioSteps.scala:6)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at cucumber.runtime.scala.ScalaBackend$$anonfun$6.apply(ScalaBackend.scala:62)
	at cucumber.runtime.scala.ScalaBackend$$anonfun$6.apply(ScalaBackend.scala:62)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at cucumber.runtime.scala.ScalaBackend.loadGlue(ScalaBackend.scala:62)
	at cucumber.runtime.Runtime.<init>(Runtime.java:92)
	at cucumber.runtime.Runtime.<init>(Runtime.java:70)
	at cucumber.runtime.Runtime.<init>(Runtime.java:66)
	at cucumber.api.cli.Main.run(Main.java:35)
	at cucumber.api.cli.Main.main(Main.java:18)
~~~

## Steps to Reproduce (for bugs)

1. In the sample project execute `sbt "run --dry-run --glue steps classpath:feature"`

**Comment by daveboden** [comment]
+1

**Comment by daveboden** [comment]
I assume it's down to Java 8 and Scala 2.12 expecting to find the "init" method in the ScalaDsl.class file (new style Traits as interfaces) rather than in ScalaDsl$class.class file (old style Traits as interface and supporting class).

Using javap to look at ScalaDsl.class from cucumber-scala_2.12-1.2.5.jar , I see it has MajorVersion = 50 which means it was compiled under Java 6.

I think the Scala 2.12 package needs to be compiled (not just run) under Java 8 to avoid this problem.

**Comment by daveboden** [comment]
I've confirmed that adding this to scala/scala_2.12/pom.xml fixes the issue:

`<pluginManagement>
	<plugins>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-compiler-plugin</artifactId>
			<version>3.5.1</version>
			<configuration>
				<encoding>UTF-8</encoding>
				<source>1.8</source>
				<target>1.8</target>
				<compilerArgument>-Werror</compilerArgument>
			</configuration>
        </plugin>
    </plugins>
</pluginManagement>`

**Comment by martintraille** [comment]
Hi daveboden, I'm experiencing the same error however my project is using SBT instead of maven, is there an equivalent solution for SBT that you know of? I have already added the ""org.apache.maven.plugins" % "maven-compiler-plugin" % "3.6.0" to my SBT build file, however I still experience the error when I run "make" compile via intellij.

**Comment by daveboden** [comment]
If you can't wait for this to be fixed in the next Cucumber release build, my advice would be:
* Clone the Cucumber build from Github.
* Make the change to the pom.xml I've suggested.
* Run the Maven *Cucumber* build with `mvn -DskipTests -pl scala/scala_2.12 -am install`

Then change your project's build to reference cucumber-scala version 1.2.6-SNAPSHOT.

From what you're saying, it sounds like you're building the Cucumber .java sources from inside your build. I'm sure you can get that to work if you need to but it doesn't seem like the obvious right thing to do (to me).

**Comment by paoloambrosio** [comment]
It would help if someone could verify PR #1091, that should fix this issue.

The code linked to this issue seems to be behaving in the same way (so failing the second example) with:
* Scala 2.12.1 and cucumber-scala 1.2.6-SNAPSHOT form the PR
* Scala 2.11.8 and cucumber-scala 1.2.5

To try it:
* From the code *root* of the PR
  * Run `mvn clean install`
* In your project
  * Change cucumber-scala from 1.2.5 to 1.2.6-SNAPSHOT
  * If using SBT, add the local Maven repository (`resolvers += Resolver.mavenLocal`)

**Comment by daveboden** [comment]
PR #1091 fixes it for my project. Tests run successfully with Scala version 2.12.0 and 2.12.2. I confirmed before I ran with 1.2.6-SNAPSHOT (which I built locally from your pull request) that the tests were still failing as I expected with version 1.2.5.

**Comment by elkingut** [comment]
Hello @paoloambrosio @daveboden some date for the deployment of the solution? I need use cucumber-scala in my project. Thanks!!

**Comment by martintraille** [comment]
Hi Dave, I am attempting the workaround you suggested, 

- Clone the Cucumber build from Github.
- Make the change to the pom.xml I've suggested.
- Run the Maven Cucumber build with mvn -DskipTests -pl scala/scala_2.12 -am install


However when I download the cucumber parent project from github via [https://github.com/cucumber/cucumber] however I cannot find the pom.xml file under (scala/scala_2.12/pom.xml) - I probably am looking at the wrong project - but can you point me in the right direction if possible?

**Comment by daveboden** [comment]
Hi. You need https://github.com/cucumber/cucumber-jvm

**Comment by martintraille** [comment]
Great, Thanks I have updated the file (within intellij). in order to run the "mvn -DskipTests -pl scala/scala_2.12 -am install" do I invoke it from the command line from the root of the project or can I do it through intellij, sorry for the questions but I am a noob and just want to make sure it's done correctly.

**Comment by fernandaalayon** [comment]
Hi @paoloambrosio & @davebassan, 
You have a date in order to upload the new version of the library with the correction of this bug, when would it be?,.
I depend on this to decide which framework to implement in my project.
Thanks

**Comment by lewismj** [comment]
I have an SBT plugin/test framework for Scala/Cucumber here https://github.com/lewismj/cucumber
I get the same issue, any ETA on when Cucumber 1.2.6 is due to ship?

**Comment by lewismj** [comment]
Hi,
I still get this error, using 1.2.6-SNAPSHOT,
java.lang.NoSuchMethodError: cucumber.api.scala.ScalaDsl.$init$(Lcucumber/api/scala/ScalaDsl

Example project:
https://github.com/lewismj/cucumber

**Comment by bhavana-git** [comment]
hi @paoloambrosio , have tried your fix. Dont see nomethod error anymore, but code within stepdefnition does not get executed.

**Comment by stela** [comment]
@bhavana-git see #1091, says step-executions and 0-arity functions fail with scala 2.12, for that pull request.

**Comment by bhavana-git** [comment]
@stela thanks , noticed it just now.

**Comment by szarnyasg** [comment]
This still does not work for us: with 2.12 we still get the exception mentioned in the first post (by @randomcoder) and later by @lewismj:

```Exception in thread "main" java.lang.NoSuchMethodError: cucumber.api.scala.ScalaDsl.$init$(Lcucumber/api/scala/ScalaDsl;```

Meanwhile, https://github.com/cucumber/cucumber-jvm/pull/1091 is still not merged. Is there any way to get this working with 2.12?

**Comment by szarnyasg** [comment]
I updated @randomcoder 's example to follow the [transition from `info.cukes` to `io.cucumber`](https://github.com/cucumber/cucumber-jvm/commit/51c86562b846329e43a9648e45dc5f73f0096589#diff-600376dffeb79835ede4a0b285078036) and use 2.0.0-SNAPSHOT, but it did not make a difference.

* repo: https://github.com/szarnyasg/cucumber-scala-2-12
* Travis build: https://travis-ci.org/szarnyasg/cucumber-scala-2-12/

**Comment by szarnyasg** [comment]
We have been struggling with this issue for some time, so I'd like to share our experience.

* @randomcoder's [original post](https://github.com/cucumber/cucumber-jvm/issues/1087#issue-196880061) has a small issue: instead of `feature`, it should be `features` on the classpath: 

   ```
   sbt "run --dry-run --glue steps classpath:features"
   ```

* @paoloambrosio's [comment](https://github.com/cucumber/cucumber-jvm/issues/1087#issuecomment-272686985) is correct and I could get the example in the issue working.

* With @szdavid92, we created a fork from @paoloambrosio's [`scala-2.12-with-java-8` branch](https://github.com/paoloambrosio/cucumber-jvm/tree/scala-2.12-with-java-8), merged this repository's [current `master` branch](https://github.com/cucumber/cucumber-jvm/tree/38571459fb9b609e23fe631d6b28ee4ebd5f6a77) and resolved the conflicts. This resulted in a working version, which is available on [my fork](https://github.com/szarnyasg/cucumber-jvm/tree/scala-2.12-with-java-8). This works with @randomcoder's example, provided that the `cucumber-scala-2-12` project also uses the [milestone Scala version](https://github.com/cucumber/cucumber-jvm/blob/master/scala/scala_2.12/pom.xml#L20), else it will throw the `java.lang.NoSuchMethodError: cucumber.api.scala.ScalaDsl.$init$(Lcucumber/api/scala/ScalaDsl;)V` error.

* Simply using the current `2.0.0-SNAPSHOT` (as deployed in the [Sonatype OSS Snapshots](https://oss.sonatype.org/content/repositories/snapshots")) repository returns in the following error:

   ```[error] (run-main-0) java.lang.NoClassDefFoundError: org/scalactic/TripleEqualsSupport$class
java.lang.NoClassDefFoundError: org/scalactic/TripleEqualsSupport$class```


   We tried to fix this by explicitly adding the appropriate [Scalactic dependency](http://mvnrepository.com/artifact/org.scalactic/scalactic_2.12/3.0.3) (`"org.scalactic" % "scalactic_2.12" % "3.0.3"`), but it made no difference.

**Comment by szarnyasg** [comment]
I created a GitHub repo and a Travis build that "sort of" reproduces the error:
* https://github.com/szarnyasg/cucumber-scala-2-12/tree/138121e1c00839448404b75cf44ebc045eb0923b
* https://travis-ci.org/szarnyasg/cucumber-scala-2-12/builds/247265792

**Comment by mpkorstanje** [comment]
@szarnyasg thanks for summarizing all that!

I've tried to solve the issue by building scala_2.12 module against java 8 but this break reflection. In some circumstances, I know not which, scala will compile the Steps into a Lambda and erase the type information.

**Comment by mpkorstanje** [comment]
Which is stupidly easy to solve in Scala because all the type information

**Comment by mpkorstanje** [comment]
Ah right. #1091 solved that already.

Does anybody have any serious objections against discontinuing support for java 8 for scala 2.12.x and up?

**Comment by szarnyasg** [comment]
#1091 was quite difficult to merge (see my attempt at https://github.com/szarnyasg/cucumber-jvm/commits/scala-2.12-with-java-8), and it only solved the NoSuchMethodError issue - I could only get it working from a projet that also uses the milestone version.

> discontinuing support for java 8 for scala 2.12.x and up?
I don't get this - AFAIK Scala 2.12 only works with Java 8.

**Comment by mpkorstanje** [comment]
Eh. Typo. Meant to say that we'll only build scala 2.12.x and up for java 8.

> I don't get this - AFAIK Scala 2.12 only works with Java 8.

Good. I was under the impression it could also work with 7.

**Comment by mpkorstanje** [comment]
> I could only get it working from a projet that also uses the milestone version.

I've updated `2.12.0-M1` to `2.12.2` and `2.11.8` to `2.11.11`.

This seems to resolve the problems.

**Comment by mpkorstanje** [comment]
I still have to test this against the reproducers but https://github.com/cucumber/cucumber-jvm/pull/1171 is passing my tests locally.

**Comment by mpkorstanje** [comment]
@stela 
> @bhavana-git see #1091, says step-executions and 0-arity functions fail with scala 2.12, for that pull request.

This appears to be a feature of Scala.
```scala
When("""^I multiply x \* y$""") { 
    z = x * y
}
```

Will execute the statement `z = x * y` which returns Unit. The Unit is then passed onto the step definition. Executing it is a no-op.

On the other hand

```scala
When("""^I multiply x \* y$""") { () =>
    z = x * y
}
```
Will return a function with the signature `() => Unit`. Which can be sensibly executed.

*Apologies if this explanation is a bit sloppy. Not that into Scala. :)

**Comment by mpkorstanje** [comment]
I was wrong. The first example utilizes call by name, the second call by reference. We allow both. The original PR broke call by name. This has been fixed.

**Comment by mpkorstanje** [comment]
@randomcoder @szarnyasg 

What is the expected out come of the reproducer. It is currently failing because the steps instance is reused between examples in the scenario. This is a bug, but the behavior also appears to have been present for a long while.

**Comment by szarnyasg** [comment]
> What is the expected out come of the reproducer.

@mpkorstanje Unfortunately, I am not an expert at Cucumber, so I cannot answer this.

**Comment by mpkorstanje** [comment]
Then I'll consider it passing. The tests are running at least.

**Comment by lewismj** [comment]
Thanks, this is great news, any idea when it may be in the SNAPSHOT build?

**Comment by mpkorstanje** [comment]
Propagation delays aside it should be available right now. 

Do note the changed groupId
```
<repository>
    <id>sonatype-snapshots</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>

<dependency>
    <groupId>io.cucumber</groupId>
    <artifactId>cucumber-java</artifactId>
    <version>2.0.0-SNAPSHOT</version>
    <scope>test</scope>
</dependency>
```

**Comment by szarnyasg** [comment]
Great, the tests now work at https://travis-ci.org/szarnyasg/cucumber-scala-2-12. Thanks @mpkorstanje!

**Comment by jecklgamis** [comment]
thanks @mpkorstanje! , looks good with oracle java  8 + scala 2.12.2 + cucucumber-scala 2.0.0-SNAPSHOT
https://github.com/jecklgamis/cucumber-jvm-scala-example

**Comment by lewismj** [comment]
Thanks, this fixed my issue: https://github.com/lewismj/cucumber/issues/28 , published an update for my sbt plugin to nexus.
