### ISSUE TITLE
Current cucumber-scala 1.0.14 doesn't work with the newest Scala 2.10.0-RC1 release

### ISSUE THREAD

**Issue by skipoleschris** [cucumber/cucumber-jvm#408]
There's a new Scala release for 2.10.0-RC1. Unfortunately the cucumber-scala jar built against 2.10.0-M6 doesn't work with this newest version. Generates the stack trace below.

I built a version locally with the pom updated to use 2.10.0-RC1 Scala library and compiler. Everything compiles, the tests all run and I've tested it in SBT (using the cucumber plugin that I maintain) and everything works fine.

Any chance of a new release that uses this new Scala version please?

Change to pom.xml:

```
124c124
<                 <version>2.10.0-M6</version>

---
>                 <version>2.10.0-RC1</version>
129c129
<                 <version>2.10.0-M6</version>

---
>                 <version>2.10.0-RC1</version>
```

The stack trace....

```
[info] Running cucumber...
[error] Exception in thread "main" java.lang.NoClassDefFoundError: scala/runtime/AbstractFunction1$mcZL$sp
[error]     at java.lang.ClassLoader.defineClass1(Native Method)
[error]     at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
[error]     at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
[error]     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
[error]     at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
[error]     at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
[error]     at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
[error]     at java.security.AccessController.doPrivileged(Native Method)
[error]     at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
[error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
[error]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
[error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
[error]     at cucumber.runtime.ScalaDsl$StepBody.register(ScalaDsl.scala:99)
[e
```
